// NEXUS ARMOR — enemy archetype definitions (data-driven).
// Difficulty multipliers from balance.difficultyMod() are applied at spawn.
import type { EnemyDef, EnemyArchetypeId } from '../core/types'

export const ENEMIES: EnemyDef[] = [
  {
    id: 'grunt',
    name: 'Grunt',
    hp: 70,
    speed: 8.5,
    accel: 16,
    turnRate: 1.9,
    turretRate: 2.0,
    radius: 1.6,
    scale: 1.0,
    weaponId: 'e_cannon',
    ai: {
      preferredRange: 22,
      strafeDir: 1,
      aimError: 0.075,
      reactionTime: 0.9,
      telegraph: 0,
      flankChance: 0.1,
      retreatHpFraction: 0.2,
      thinkInterval: 0.28,
    },
    colors: { hull: 0x8a3b34, turret: 0x6f2f2a, accent: 0xe0a898 },
    xpReward: 22,
    creditReward: 24,
  },
  {
    id: 'rusher',
    name: 'Rusher',
    hp: 45,
    speed: 13.5,
    accel: 24,
    turnRate: 2.7,
    turretRate: 2.6,
    radius: 1.4,
    scale: 0.85,
    weaponId: 'e_ac',
    ai: {
      preferredRange: 12,
      strafeDir: -1,
      aimError: 0.09,
      reactionTime: 0.6,
      telegraph: 0,
      flankChance: 0.8,
      retreatHpFraction: 0.15,
      thinkInterval: 0.22,
    },
    colors: { hull: 0xa0523c, turret: 0x84412f, accent: 0xf0c0a0 },
    xpReward: 26,
    creditReward: 30,
  },
  {
    id: 'sniper',
    name: 'Sniper',
    hp: 55,
    speed: 7,
    accel: 14,
    turnRate: 1.6,
    turretRate: 1.6,
    radius: 1.5,
    scale: 0.95,
    weaponId: 'e_rail',
    ai: {
      preferredRange: 40,
      strafeDir: 1,
      aimError: 0.02,
      reactionTime: 1.1,
      telegraph: 0.65, // red aim line before firing — the counterplay window
      flankChance: 0,
      retreatHpFraction: 0.35,
      thinkInterval: 0.3,
    },
    colors: { hull: 0x7c3a55, turret: 0x632e45, accent: 0xff9ab0 },
    xpReward: 34,
    creditReward: 40,
  },
  {
    id: 'brute',
    name: 'Brute',
    hp: 160,
    speed: 6,
    accel: 11,
    turnRate: 1.3,
    turretRate: 1.4,
    radius: 2.1,
    scale: 1.3,
    weaponId: 'e_brute',
    ai: {
      preferredRange: 16,
      strafeDir: 1,
      aimError: 0.06,
      reactionTime: 1.0,
      telegraph: 0,
      flankChance: 0,
      retreatHpFraction: 0.1,
      thinkInterval: 0.35,
    },
    colors: { hull: 0x6b2f2f, turret: 0x552424, accent: 0xe89080 },
    xpReward: 55,
    creditReward: 70,
  },
  {
    id: 'boss',
    name: 'GOLIATH',
    hp: 700,
    speed: 4.5,
    accel: 8,
    turnRate: 1.0,
    turretRate: 1.1,
    radius: 3.2,
    scale: 2.1,
    weaponId: 'e_brute',
    ai: {
      preferredRange: 20,
      strafeDir: 1,
      aimError: 0.05,
      reactionTime: 0.8,
      telegraph: 0.4,
      flankChance: 0,
      retreatHpFraction: 0,
      thinkInterval: 0.3,
    },
    colors: { hull: 0x4a1f1f, turret: 0x381616, accent: 0xff5a3c },
    xpReward: 300,
    creditReward: 420,
    label: 'GOLIATH',
  },
]

export const ENEMY_BY_ID: Record<EnemyArchetypeId, EnemyDef> = Object.fromEntries(
  ENEMIES.map((e) => [e.id, e]),
) as Record<EnemyArchetypeId, EnemyDef>
