// NEXUS ARMOR — mission definitions (data-driven campaign).
// Wave `delay` semantics:
//   eliminate missions → seconds AFTER previous wave cleared
//   survive / destroy / boss missions → absolute seconds since battle start
import type { MissionDef } from '../core/types'

export const MISSIONS: MissionDef[] = [
  {
    id: 'm01',
    name: 'First Contact',
    mapId: 'dry_docks',
    briefing: 'Raiders probed the docks overnight. Take the Jackal out and clear the scouts.',
    objective: { type: 'eliminate' },
    waves: [{ delay: 0, spawns: [{ archetype: 'grunt', count: 2, edge: 'n' }] }],
    difficulty: 1,
    rewards: { credits: 150, xp: 80 },
    unlockAfter: null,
    seed: 1001,
    hints: ['WASD to drive', 'Aim with the mouse — click to fire', 'Your front plate bounces shells. Face the enemy.'],
  },
  {
    id: 'm02',
    name: 'Scrap Line',
    mapId: 'dry_docks',
    briefing: 'The raiders keep coming through the scrap line. Sweep it, wave by wave.',
    objective: { type: 'eliminate' },
    waves: [
      { delay: 0, spawns: [{ archetype: 'grunt', count: 3, edge: 'any' }] },
      { delay: 2, spawns: [{ archetype: 'grunt', count: 2, edge: 'e' }, { archetype: 'rusher', count: 1, edge: 'w' }] },
      { delay: 2, spawns: [{ archetype: 'grunt', count: 2, edge: 'any' }, { archetype: 'rusher', count: 2, edge: 'n' }] },
    ],
    difficulty: 2,
    rewards: { credits: 220, xp: 120 },
    unlockAfter: 'm01',
    seed: 1002,
  },
  {
    id: 'm03',
    name: 'Hold the Yard',
    mapId: 'dry_docks',
    briefing: 'Convoy repairs need 90 seconds. Hold the yard until the last truck rolls.',
    objective: { type: 'survive', duration: 90 },
    waves: [
      { delay: 0, spawns: [{ archetype: 'grunt', count: 2, edge: 'n' }] },
      { delay: 15, spawns: [{ archetype: 'grunt', count: 2, edge: 'e' }, { archetype: 'rusher', count: 1, edge: 'w' }] },
      { delay: 30, spawns: [{ archetype: 'grunt', count: 3, edge: 'any' }] },
      { delay: 45, spawns: [{ archetype: 'rusher', count: 2, edge: 'n' }, { archetype: 'sniper', count: 1, edge: 'e' }] },
      { delay: 60, spawns: [{ archetype: 'grunt', count: 3, edge: 'any' }, { archetype: 'rusher', count: 1, edge: 'w' }] },
      { delay: 75, spawns: [{ archetype: 'grunt', count: 2, edge: 'e' }, { archetype: 'brute', count: 1, edge: 'n' }] },
    ],
    difficulty: 3,
    rewards: { credits: 260, xp: 150 },
    unlockAfter: 'm02',
    seed: 1003,
    hints: ['Snipers show a red line before firing — break line of sight.'],
  },
  {
    id: 'm04',
    name: 'Bunker Rush',
    mapId: 'canyon_outpost',
    briefing: 'Three raider munitions bunkers feed their advance. Demolish all of them.',
    objective: { type: 'destroy', count: 3 },
    waves: [
      { delay: 0, spawns: [{ archetype: 'grunt', count: 3, edge: 'any' }] },
      { delay: 25, spawns: [{ archetype: 'grunt', count: 2, edge: 'e' }, { archetype: 'rusher', count: 2, edge: 'w' }] },
      { delay: 50, spawns: [{ archetype: 'brute', count: 1, edge: 'n' }, { archetype: 'sniper', count: 1, edge: 'e' }] },
    ],
    difficulty: 3,
    rewards: { credits: 300, xp: 170 },
    unlockAfter: 'm03',
    seed: 1004,
    hints: ['Bunkers are the glowing structures — put shells into them.'],
  },
  {
    id: 'm05',
    name: 'Canyon Ambush',
    mapId: 'canyon_outpost',
    briefing: 'They dug marksmen into the canyon rim. Flush them out — watch those firing lines.',
    objective: { type: 'eliminate' },
    waves: [
      { delay: 0, spawns: [{ archetype: 'grunt', count: 3, edge: 'any' }] },
      { delay: 2, spawns: [{ archetype: 'sniper', count: 2, edge: 'n' }, { archetype: 'grunt', count: 2, edge: 'w' }] },
      { delay: 2, spawns: [{ archetype: 'rusher', count: 3, edge: 'e' }, { archetype: 'grunt', count: 2, edge: 's' }] },
    ],
    difficulty: 4,
    rewards: { credits: 340, xp: 190 },
    unlockAfter: 'm04',
    seed: 1005,
  },
  {
    id: 'm06',
    name: 'Night Shift',
    mapId: 'foundry',
    briefing: 'Raiders hit the foundry at night. Survive the shift — it gets worse before dawn.',
    objective: { type: 'survive', duration: 120 },
    waves: [
      { delay: 0, spawns: [{ archetype: 'grunt', count: 3, edge: 'any' }] },
      { delay: 20, spawns: [{ archetype: 'rusher', count: 3, edge: 'e' }] },
      { delay: 40, spawns: [{ archetype: 'grunt', count: 2, edge: 'n' }, { archetype: 'sniper', count: 2, edge: 'w' }] },
      { delay: 60, spawns: [{ archetype: 'brute', count: 2, edge: 'n' }] },
      { delay: 80, spawns: [{ archetype: 'grunt', count: 3, edge: 'any' }, { archetype: 'rusher', count: 2, edge: 'e' }] },
      { delay: 100, spawns: [{ archetype: 'brute', count: 1, edge: 'n' }, { archetype: 'sniper', count: 2, edge: 'w' }] },
    ],
    difficulty: 5,
    rewards: { credits: 400, xp: 220 },
    unlockAfter: 'm05',
    seed: 1006,
  },
  {
    id: 'm07',
    name: 'Foundry Sweep',
    mapId: 'foundry',
    briefing: 'Four converter stacks are being stripped for parts. Demolition order is yours to pick.',
    objective: { type: 'destroy', count: 4 },
    waves: [
      { delay: 0, spawns: [{ archetype: 'grunt', count: 3, edge: 'any' }, { archetype: 'rusher', count: 1, edge: 'e' }] },
      { delay: 30, spawns: [{ archetype: 'sniper', count: 2, edge: 'w' }, { archetype: 'grunt', count: 2, edge: 'n' }] },
      { delay: 55, spawns: [{ archetype: 'brute', count: 2, edge: 'e' }] },
      { delay: 75, spawns: [{ archetype: 'rusher', count: 3, edge: 'w' }, { archetype: 'grunt', count: 2, edge: 's' }] },
    ],
    difficulty: 6,
    rewards: { credits: 460, xp: 250 },
    unlockAfter: 'm06',
    seed: 1007,
  },
  {
    id: 'm08',
    name: 'The Gauntlet',
    mapId: 'canyon_outpost',
    briefing: 'Everything they have left, all at once, down the canyon. Good hunting.',
    objective: { type: 'eliminate' },
    waves: [
      { delay: 0, spawns: [{ archetype: 'grunt', count: 3, edge: 'any' }] },
      { delay: 2, spawns: [{ archetype: 'rusher', count: 2, edge: 'e' }, { archetype: 'sniper', count: 2, edge: 'n' }] },
      { delay: 2, spawns: [{ archetype: 'grunt', count: 3, edge: 'w' }, { archetype: 'brute', count: 1, edge: 'n' }] },
      { delay: 2, spawns: [{ archetype: 'brute', count: 2, edge: 'e' }, { archetype: 'sniper', count: 2, edge: 's' }] },
    ],
    difficulty: 7,
    rewards: { credits: 520, xp: 290 },
    unlockAfter: 'm07',
    seed: 1008,
  },
  {
    id: 'm09',
    name: 'Last Stand',
    mapId: 'foundry',
    briefing: 'The foundry is the last beacon this side of the pass. Survive 150 seconds.',
    objective: { type: 'survive', duration: 150 },
    waves: [
      { delay: 0, spawns: [{ archetype: 'grunt', count: 3, edge: 'any' }] },
      { delay: 25, spawns: [{ archetype: 'rusher', count: 4, edge: 'e' }] },
      { delay: 50, spawns: [{ archetype: 'grunt', count: 2, edge: 'n' }, { archetype: 'sniper', count: 3, edge: 'w' }] },
      { delay: 75, spawns: [{ archetype: 'brute', count: 2, edge: 'e' }, { archetype: 'rusher', count: 2, edge: 'w' }] },
      { delay: 100, spawns: [{ archetype: 'grunt', count: 4, edge: 'any' }] },
      { delay: 125, spawns: [{ archetype: 'brute', count: 2, edge: 'n' }, { archetype: 'sniper', count: 2, edge: 'e' }] },
    ],
    difficulty: 8,
    rewards: { credits: 600, xp: 330 },
    unlockAfter: 'm08',
    seed: 1009,
  },
  {
    id: 'm10',
    name: 'GOLIATH',
    mapId: 'canyon_outpost',
    briefing: 'They built something terrible in the canyon. It has your name on its guns. End this.',
    objective: { type: 'boss' },
    waves: [
      { delay: 0, spawns: [{ archetype: 'grunt', count: 2, edge: 'n' }] },
      { delay: 8, spawns: [{ archetype: 'boss', count: 1, edge: 'n' }] },
      { delay: 40, spawns: [{ archetype: 'grunt', count: 2, edge: 'w' }, { archetype: 'rusher', count: 2, edge: 'e' }] },
      { delay: 80, spawns: [{ archetype: 'sniper', count: 2, edge: 's' }] },
    ],
    difficulty: 10,
    rewards: { credits: 800, xp: 450 },
    unlockAfter: 'm09',
    seed: 1010,
    hints: ['GOLIATH hits hard from range. Use the canyon walls — never trade in the open.'],
  },
]

export const MISSION_BY_ID: Record<string, MissionDef> = Object.fromEntries(MISSIONS.map((m) => [m.id, m]))
