// NEXUS ARMOR — player tank hull definitions (data-driven; add a row → appears in Garage).
import type { AbilityDef, TankDef } from '../core/types'

export const ABILITIES: Record<string, AbilityDef> = {
  overdrive: {
    id: 'overdrive',
    name: 'Overdrive',
    description: '+60% speed and +50% reload speed for 4s.',
    cooldown: 18,
    duration: 4,
  },
  repair: {
    id: 'repair',
    name: 'Field Repair',
    description: 'Restore 30% of max HP over 2s.',
    cooldown: 25,
    duration: 2,
  },
  focus: {
    id: 'focus',
    name: 'Focus Shot',
    description: 'Next shot within 5s deals 2.2× damage and pierces all targets.',
    cooldown: 20,
    duration: 5,
  },
  aegis: {
    id: 'aegis',
    name: 'Aegis',
    description: 'Take 50% less damage for 4s.',
    cooldown: 22,
    duration: 4,
  },
}

export const TANKS: TankDef[] = [
  {
    id: 'scout',
    name: 'VX-1 “Jackal”',
    role: 'Light / Scout',
    description: 'Fast flanker with a rapid autocannon. Paper armor — win by never standing still.',
    price: 0,
    hp: 105,
    speed: 16,
    accel: 26,
    turnRate: 2.6,
    turretRate: 3.4,
    radius: 1.5,
    weaponId: 'autocannon',
    abilityId: 'overdrive',
    scale: 0.9,
    colors: { hull: 0x8f9a5a, turret: 0x7c874c, accent: 0xd9d9a0 },
    armor: { front: 0.6, side: 1.0, rear: 1.5 },
  },
  {
    id: 'medium',
    name: 'VX-4 “Bulwark”',
    role: 'Medium / Brawler',
    description: 'The reliable all-rounder. Solid gun, solid plate — hold the line and trade fire.',
    price: 1200,
    hp: 150,
    speed: 12,
    accel: 20,
    turnRate: 2.0,
    turretRate: 2.6,
    radius: 1.7,
    weaponId: 'cannon',
    abilityId: 'repair',
    scale: 1.0,
    colors: { hull: 0x6f7d52, turret: 0x5d6a45, accent: 0xc9c98f },
    armor: { front: 0.5, side: 0.95, rear: 1.45 },
  },
  {
    id: 'td',
    name: 'VX-7 “Longbow”',
    role: 'Tank Destroyer',
    description: 'A railgun that punches through anything — including the tank behind the tank. Fragile, slow turret.',
    price: 2800,
    hp: 120,
    speed: 10.5,
    accel: 18,
    turnRate: 1.7,
    turretRate: 1.9,
    radius: 1.65,
    weaponId: 'railgun',
    abilityId: 'focus',
    scale: 1.05,
    colors: { hull: 0x77705e, turret: 0x655f50, accent: 0xcfc6a8 },
    armor: { front: 0.55, side: 1.05, rear: 1.5 },
  },
  {
    id: 'heavy',
    name: 'VX-9 “Mammoth”',
    role: 'Heavy / Breaker',
    description: 'A walking bunker with a howitzer. Slow, but you will have to actually kill it.',
    price: 5200,
    hp: 240,
    speed: 8.5,
    accel: 14,
    turnRate: 1.4,
    turretRate: 1.8,
    radius: 2.0,
    weaponId: 'howitzer',
    abilityId: 'aegis',
    scale: 1.2,
    colors: { hull: 0x5e6653, turret: 0x4c5342, accent: 0xb8bfa0 },
    armor: { front: 0.42, side: 0.85, rear: 1.35 },
  },
]

export const TANK_BY_ID: Record<string, TankDef> = Object.fromEntries(TANKS.map((t) => [t.id, t]))
export const STARTER_TANK: TankRoleId = 'scout'
import type { TankRoleId } from '../core/types'
