// NEXUS ARMOR — weapon definitions (data-driven).
import type { WeaponDef } from '../core/types'

const defs: WeaponDef[] = [
  // --- player weapons ---
  {
    id: 'autocannon',
    name: 'AC-20 Autocannon',
    damage: 9,
    reloadTime: 0.3,
    projectileSpeed: 85,
    splashRadius: 0,
    splashFalloff: 0,
    pierce: 0,
    spread: 0.028,
    normalizes: false,
    tracerColor: 0xffe0a0,
    sound: 'autocannon',
  },
  {
    id: 'cannon',
    name: 'M-75 Cannon',
    damage: 34,
    reloadTime: 2.2,
    projectileSpeed: 62,
    splashRadius: 2.2,
    splashFalloff: 0.35,
    pierce: 0,
    spread: 0.008,
    normalizes: false,
    tracerColor: 0xffc873,
    sound: 'cannon',
  },
  {
    id: 'railgun',
    name: 'LX-9 Railgun',
    damage: 88,
    reloadTime: 3.4,
    projectileSpeed: 150,
    splashRadius: 0,
    splashFalloff: 0,
    pierce: 2,
    spread: 0,
    normalizes: true, // APFSDS — never ricochets
    tracerColor: 0x8ef5ff,
    sound: 'railgun',
  },
  {
    id: 'howitzer',
    name: 'HB-152 Howitzer',
    damage: 56,
    reloadTime: 3.2,
    projectileSpeed: 48,
    splashRadius: 5.5,
    splashFalloff: 0.5,
    pierce: 0,
    spread: 0.012,
    normalizes: false,
    tracerColor: 0xffb060,
    sound: 'howitzer',
  },
  // --- enemy weapons (scaled by difficulty at spawn) ---
  {
    id: 'e_cannon',
    name: 'Enemy Cannon',
    damage: 14,
    reloadTime: 2.6,
    projectileSpeed: 55,
    splashRadius: 1.6,
    splashFalloff: 0.3,
    pierce: 0,
    spread: 0.01,
    normalizes: false,
    tracerColor: 0xff9a6a,
    sound: 'cannon',
  },
  {
    id: 'e_ac',
    name: 'Enemy Autocannon',
    damage: 4,
    reloadTime: 0.42,
    projectileSpeed: 80,
    splashRadius: 0,
    splashFalloff: 0,
    pierce: 0,
    spread: 0.06,
    normalizes: false,
    tracerColor: 0xffb08a,
    sound: 'autocannon',
  },
  {
    id: 'e_rail',
    name: 'Enemy Marksman Gun',
    damage: 30,
    reloadTime: 3.8,
    projectileSpeed: 130,
    splashRadius: 0,
    splashFalloff: 0,
    pierce: 0,
    spread: 0,
    normalizes: true,
    tracerColor: 0xff7a9e,
    sound: 'sniper',
  },
  {
    id: 'e_brute',
    name: 'Siege Gun',
    damage: 24,
    reloadTime: 3.4,
    projectileSpeed: 42,
    splashRadius: 4.5,
    splashFalloff: 0.55,
    pierce: 0,
    spread: 0.02,
    normalizes: false,
    tracerColor: 0xff6a4a,
    sound: 'brute',
  },
]

export const WEAPONS: Record<string, WeaponDef> = Object.fromEntries(defs.map((w) => [w.id, w]))
